server:
  address: 0.0.0.0
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #Local
    #url: jdbc:mysql://localhost:3306/recaudo?serverTimezone=UTC
    #username: root
    #password:
    #para docker
    # url: jdbc:postgresql://host.docker.internal:3306/recaudo?serverTimezone=UTC
    #username: recaudoapp
    #password: R3c4uD0-DB
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: true
      max-request-size: 15MB
      file-size-threshold: 2KB
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

#t0ll-p4y-js0n-w3b-70k3n-s3cr37-k3y
app:
  jwt-secret: dDBsbC1wNHktanMwbi13M2ItNzBrM24tczNjcjM3LWszeQ==
  jwt-expiration-milliseconds: 60000
  jwt-token-type: Bearer
#  security:
#    user:
#      name: ikarlox
#      password: 123

logging:
  level:
    org:
      springframework:
        cache: DEBUG
        interceptor: DEBUG
    hibernate:
      SQL: debug
      type:
        descriptor:
          sql: trace

message:
  exception:
    general: Ha ocurrido un error
    internal-server-error: Estamos presentando problemas, intente de nuevo mas tarde
    method-not-allow: Método de petición no permitido
    not-found: Información no encontrada
    bad-request: Petición no valida
    constraint-violation: Se ha infringido una integridad de datos
    username-not-found: No se ha encontrado el usuario
    bad-credentials: Credenciales incorrectos
    unauthorized: Acceso denegado
    forbidden: Acceso restringido
    media-type-no-supported: Media type unsopported
    expired-code: Código de verificación expirado

authorization-request:
  headers:
    application-id-internal: kata-02
    application-id-external: kata-01
  credentials:
    api-key-internal: 1234
    api-key-external: 1234